In [1]:
import numpy as np
import pandas as pd

In [2]:
#Q1
arr = np.arange(6)
print(arr.dtype)

int32


In [3]:
#Q2
arr = np.array([1.0, 2.0])
print(arr.dtype == np.float64)


True


In [5]:
#Q3
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [6]:
#Q4
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.astype(np.float32)
print(arr)

[1. 2. 3.]


In [7]:
#Q4
arr = np.array([1.1, 2.2], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)

[1.1 2.2]


In [18]:
# 5. Given a NumPy array arr with float64 data type, convert it to float32.
float64_arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
float32_arr_reduced = float64_arr.astype(np.float32)

print("Original float64 array:", float64_arr, "Dtype:", float64_arr.dtype)
print("Converted float32 array:", float32_arr_reduced, "Dtype:", float32_arr_reduced.dtype)


Original float64 array: [1.12345679 2.98765432] Dtype: float64
Converted float32 array: [1.1234568 2.9876542] Dtype: float32


In [19]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr_for_attrs = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr_for_attrs)

print("Array:\n", arr_for_attrs)
print(f"Shape: {shape}, Size: {size}, Data Type: {dtype}")


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3), Size: 6, Data Type: int32


In [20]:
# 7. Create a function array_dimension that returns the dimensionality of a NumPy array.
def array_dimension(arr):
    return arr.ndim

arr_3d = np.array([[[1], [2]], [[3], [4]]])

print("Array:\n", arr_3d)
print("Dimension:", array_dimension(arr_3d))


Array:
 [[[1]
  [2]]

 [[3]
  [4]]]
Dimension: 3


In [21]:
# 8. Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr_for_bytes = np.array([1, 2, 3], dtype=np.int64)
itemsize, nbytes = item_size_info(arr_for_bytes)

print("Array:", arr_for_bytes)
print(f"Item Size (bytes): {itemsize}, Total Size (bytes): {nbytes}")


Array: [1 2 3]
Item Size (bytes): 8, Total Size (bytes): 24


In [12]:
# 9. Create a function array_strides that returns the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides

arr_for_strides = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
# Strides: (bytes to go to next row, bytes to go to next column) -> (3*4, 4)

print("Array:\n", arr_for_strides)
print("Strides (bytes):", array_strides(arr_for_strides))


In [22]:
# 10. Design a function shape_stride_relationship that returns the shape and strides of the given array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr_for_shape_stride = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int16)
# Shape: (3, 2). Strides: (bytes for next row, bytes for next col) -> (2*2, 2)
shape, strides = shape_stride_relationship(arr_for_shape_stride)
print("Array:\n", arr_for_shape_stride)
print(f"Shape: {shape}, Strides: {strides}")


Array:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2), Strides: (4, 2)


In [23]:
# 11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)
print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [24]:
# 12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# 13. Write a function generate_range_array (start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
print(generate_range_array(10, 50, 5))


[10 15 20 25 30 35 40 45]


In [26]:
# 14. Design a function generate_linear_space(start, stop, num) for equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print(generate_linear_space(0, 10, 5))


[ 0.   2.5  5.   7.5 10. ]


In [27]:
# 15. Create a function create_identity_matrix(n) using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)
print(create_identity_matrix(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
# 16. Write a function that converts a Python list into a NumPy array.
def list_to_numpy_array(py_list):
    return np.array(py_list)
my_list = [[1, 2], [3, 4]]
print(list_to_numpy_array(my_list))


[[1 2]
 [3 4]]


In [29]:
# 17. Create a NumPy array and use numpy.view() to create a new view with the same data.
original_arr = np.array([1, 2, 3, 4])
view_arr = original_arr.view()
view_arr[0] = 100
print("Original Array:", original_arr)
print("View Array:", view_arr)


Original Array: [100   2   3   4]
View Array: [100   2   3   4]


In [30]:
# 18. Write a function to concatenate two NumPy arrays along a specified axis.
def concat_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("Concatenate along axis 0 (rows):\n", concat_arrays(a, b, axis=0))
print("Concatenate along axis 1 (cols):\n", concat_arrays(a, b.T, axis=1))

Concatenate along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]]
Concatenate along axis 1 (cols):
 [[1 2 5]
 [3 4 6]]


In [32]:
# 19. Concatenate two arrays with different shapes horizontally using numpy.concatenate.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]]) # arr2 has same number of rows (2)
concatenated_h = np.concatenate((arr1, arr2), axis=1)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Horizontally concatenated:\n", concatenated_h)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5]
 [6]]
Horizontally concatenated:
 [[1 2 5]
 [3 4 6]]


In [33]:
# 20. Vertically stack multiple arrays from a list using numpy.vstack.
array_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
stacked_v = np.vstack(array_list)

print("List of arrays:", array_list)
print("Vertically stacked array:\n", stacked_v)


List of arrays: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# 21. Write a function to generate an array of integers within a specified range (inclusive) with a step.
def generate_inclusive_range(start, stop, step):
    return np.arange(start, stop + 1, step)
print(generate_inclusive_range(1, 10, 2))


[1 3 5 7 9]


In [35]:
# 22. Generate 10 equally spaced values between 0 and 1 using NumPy.
spaced_values = np.linspace(0, 1, 10)
print(spaced_values)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [36]:
# 23. Create 5 logarithmically spaced values between 1 and 1000.
log_values = np.logspace(0, 3, 5) # 10**0=1, 10**3=1000
print(log_values)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [37]:
import pandas as pd

# 24. Create a Pandas DataFrame from a NumPy array.
random_np_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(random_np_array, columns=['Col1', 'Col2', 'Col3'])
print("NumPy Array:\n", random_np_array)
print("Pandas DataFrame:\n", df)


NumPy Array:
 [[90 22 99]
 [95 50 79]
 [29 22 62]
 [16 39 16]
 [47 58 66]]
Pandas DataFrame:
    Col1  Col2  Col3
0    90    22    99
1    95    50    79
2    29    22    62
3    16    39    16
4    47    58    66


In [38]:
# 25. Write a function to replace all negative values in a specific column with zeros.
def replace_negatives_in_col(df, col_name):
    df[col_name] = np.maximum(df[col_name], 0)
    return df

data = {'A': [1, 2, -3, 4], 'B': [-5, 6, 7, -8], 'C': [9, 0, -1, 2]}
df_neg = pd.DataFrame(data)
print("Original DataFrame:\n", df_neg)
df_modified = replace_negatives_in_col(df_neg.copy(), 'B')
print("Modified DataFrame (Column 'B'):\n", df_modified)

Original DataFrame:
    A  B  C
0  1 -5  9
1  2  6  0
2 -3  7 -1
3  4 -8  2
Modified DataFrame (Column 'B'):
    A  B  C
0  1  0  9
1  2  6  0
2 -3  7 -1
3  4  0  2


In [39]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2] 
print("Array:", arr)
print("Third Element:", third_element)


Array: [10 20 30 40 50]
Third Element: 30


In [40]:
# 27. Retrieve the element at index (1, 2) from a 2D array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element_1_2 = arr_2d[1, 2]
print("Array:\n", arr_2d)
print("Element at (1, 2):", element_1_2)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6


In [41]:
# 28. Extract elements greater than 5 using boolean indexing.
arr = np.array([1, 8, 3, 10, 5, 6])
greater_than_5 = arr[arr > 5]
print("Array:", arr)
print("Elements > 5:", greater_than_5)

Array: [ 1  8  3 10  5  6]
Elements > 5: [ 8 10  6]


In [42]:
# 29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr = np.arange(10)
# Slicing is exclusive of the end index, so we use index 6 to include element at index 5.
sliced_arr = arr[2:6]
print("Array:", arr)
print("Elements from index 2 to 5:", sliced_arr)

Array: [0 1 2 3 4 5 6 7 8 9]
Elements from index 2 to 5: [2 3 4 5]


In [43]:
# 30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_source = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
sub_array = arr_source[0:2, 2:4] #This would be [[2,3],[6,7]]
# Let's create an array from which [[2,3],[5,6]] can be sliced
arr_2d_q30 = np.array([[0,1,2,3],[4,5,6,7]])
sub_array_sliced = arr_2d_q30[0:2, 2:4] #This gives [[2,3],[6,7]].
arr_2d_q30 = np.array([[1,2,3],[4,5,6]])
sub_array_sliced = arr_2d_q30[0:2,1:3]
print("Original Array:\n", arr_2d_q30)
print("Sliced sub-array:\n", sub_array_sliced)


Original Array:
 [[1 2 3]
 [4 5 6]]
Sliced sub-array:
 [[2 3]
 [5 6]]


In [44]:
# 31. Extract elements based on indices from a 2D array.
arr_2d = np.arange(12).reshape(3, 4)
indices = ([0, 1, 2], [1, 2, 3])
extracted_elements = arr_2d[indices]
print("Array:\n", arr_2d)
print("Extracted elements at (0,1), (1,2), (2,3):", extracted_elements)


Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Extracted elements at (0,1), (1,2), (2,3): [ 1  6 11]


In [45]:
# 32. Filter elements greater than a threshold using boolean indexing.
arr = np.array([[10, 25, 5], [40, 15, 30]])
threshold = 20
filtered_elements = arr[arr > threshold]
print("Array:\n", arr)
print("Elements > 20:", filtered_elements)

Array:
 [[10 25  5]
 [40 15 30]]
Elements > 20: [25 40 30]


In [46]:
# 33. Extract specific elements from a 3D array using separate index arrays.
arr_3d = np.arange(24).reshape(2, 3, 4)

idx0 = np.array([0, 1, 0])
idx1 = np.array([0, 1, 2])
idx2 = np.array([1, 2, 3])
extracted_3d = arr_3d[idx0, idx1, idx2]
print("Array:\n", arr_3d)
print("Extracted elements:", extracted_3d)


Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Extracted elements: [ 1 18 11]


In [47]:
# 34. Return elements satisfying two boolean conditions.
arr = np.arange(20)
filtered_arr = arr[(arr > 5) & (arr % 2 == 0)]
print("Array:", arr)
print("Elements > 5 AND are even:", filtered_arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements > 5 AND are even: [ 6  8 10 12 14 16 18]


In [48]:
# 35. Extract elements from a 2D array using separate row and column index arrays.
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
extracted = arr_2d[row_indices, col_indices]
print("Array:\n", arr_2d)
print("Row indices:", row_indices)
print("Column indices:", col_indices)
print("Extracted elements:", extracted)

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row indices: [0 1 2]
Column indices: [2 1 0]
Extracted elements: [30 50 70]


In [49]:
# 36. Add scalar 5 to every element of an array using broadcasting.
arr = np.array([[1, 2], [3, 4]])
result = arr + 5
print("Original Array:\n", arr)
print("Array after adding 5:\n", result)

Original Array:
 [[1 2]
 [3 4]]
Array after adding 5:
 [[6 7]
 [8 9]]


In [50]:
# 37. Multiply each row of a (3,4) array by corresponding elements of a (1,3) array.
arr_3x4 = np.ones((3, 4))
arr_3x1 = np.array([[2], [3], [4]]) # Shape (3,1)
result = arr_3x4 * arr_3x1
print("Array (3,4):\n", arr_3x4)
print("Array (3,1):\n", arr_3x1)
print("Result:\n", result)

Array (3,4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array (3,1):
 [[2]
 [3]
 [4]]
Result:
 [[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [51]:
# 38. Add a (1,4) array to every row of a (4,3) array using broadcasting.
arr_4x3 = np.ones((4, 3))
arr_1x3 = np.arange(3).reshape(1, 3) # Shape (1,3)
result = arr_4x3 + arr_1x3
print("Array (4,3):\n", arr_4x3)
print("Array (1,3):\n", arr_1x3)
print("Result:\n", result)

Array (4,3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array (1,3):
 [[0 1 2]]
Result:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [52]:
# 39. Add two arrays of shapes (3,1) and (1, 3) using broadcasting.
arr1 = np.arange(3).reshape(3, 1) 
arr2 = np.arange(3).reshape(1, 3) 
result = arr1 + arr2
print("Array 1 (3,1):\n", arr1)
print("Array 2 (1,3):\n", arr2)
print("Result of addition:\n", result)

Array 1 (3,1):
 [[0]
 [1]
 [2]]
Array 2 (1,3):
 [[0 1 2]]
Result of addition:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [53]:
# 40. Handle shape incompatibility during multiplication between (2,3) and (2,2) arrays.
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 2))
print("Attempting to multiply array of shape (2,3) with array of shape (2,2).")
try:
    result = arr1 * arr2
except ValueError as e:
    print("Caught expected error:", e)

Attempting to multiply array of shape (2,3) with array of shape (2,2).
Caught expected error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [54]:
# 41. Calculate column-wise mean of a 2D array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col_mean = np.mean(arr_2d, axis=0)
print("Array:\n", arr_2d)
print("Column-wise mean:", col_mean)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column-wise mean: [4. 5. 6.]


In [55]:
# 42. Find maximum value in each row.
arr_2d = np.array([[1, 5, 3], [8, 2, 6]])
row_max = np.max(arr_2d, axis=1)
print("Array:\n", arr_2d)
print("Maximum value in each row:", row_max)

Array:
 [[1 5 3]
 [8 2 6]]
Maximum value in each row: [5 8]


In [56]:
# 43. Find indices of maximum values in each column.
arr_2d = np.array([[1, 9, 3], [8, 2, 6], [4, 5, 7]])
max_indices_col = np.argmax(arr_2d, axis=0)
print("Array:\n", arr_2d)
print("Indices of max values in each column:", max_indices_col)

Array:
 [[1 9 3]
 [8 2 6]
 [4 5 7]]
Indices of max values in each column: [1 0 2]


In [57]:
# 44. Apply a custom function to compute moving sum along rows.
def moving_sum(arr, window_size=2):
    return np.convolve(arr, np.ones(window_size), 'valid')

arr_2d = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])
moving_sums = np.apply_along_axis(moving_sum, axis=1, arr=arr_2d)
print("Array:\n", arr_2d)
print("Moving sum with window size 2:\n", moving_sums)

Array:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]
Moving sum with window size 2:
 [[ 3.  5.  7.  9.]
 [30. 50. 70. 90.]]


In [58]:
# 45. Check if all elements in each column are even.
arr_2d = np.array([[2, 4, 6], [8, 3, 10], [12, 14, 16]])
all_even_cols = np.all(arr_2d % 2 == 0, axis=0)
print("Array:\n", arr_2d)
print("Are all elements in each column even?", all_even_cols)



Array:
 [[ 2  4  6]
 [ 8  3 10]
 [12 14 16]]
Are all elements in each column even? [ True False  True]


In [59]:
# 46. Reshape a given array into dimensions m x n.
arr = np.arange(12)
m, n = 3, 4
reshaped_arr = arr.reshape(m, n)
print("Original array:", arr)
print(f"Reshaped array ({m}x{n}):\n", reshaped_arr)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
# 47. Return a flattened version of a given matrix.
matrix = np.array([[1, 2], [3, 4]])
flattened_arr = matrix.flatten()
print("Original Matrix:\n", matrix)
print("Flattened Array:", flattened_arr)

Original Matrix:
 [[1 2]
 [3 4]]
Flattened Array: [1 2 3 4]


In [61]:
# 48. Concatenate two arrays along a specified axis. (Same as Q18)
def concat_arrays_q48(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2]])
b = np.array([[3, 4]])
print("Concatenate along axis 0 (rows):\n", concat_arrays_q48(a, b, axis=0))

Concatenate along axis 0 (rows):
 [[1 2]
 [3 4]]


In [62]:
# 49. Split an array into sub-arrays along a specified axis.
arr = np.arange(9)
sub_arrays = np.split(arr, 3)
print("Original array:", arr)
print("Split sub-arrays:", sub_arrays)

Original array: [0 1 2 3 4 5 6 7 8]
Split sub-arrays: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [63]:
# 50. Insert and delete elements at specified indices from an array.
arr = np.array([1, 2, 3, 4, 5])
arr_inserted = np.insert(arr, 2, 10)
print("Original array:", arr)
print("After insertion:", arr_inserted)
arr_deleted = np.delete(arr_inserted, 3)
print("After deletion:", arr_deleted)


Original array: [1 2 3 4 5]
After insertion: [ 1  2 10  3  4  5]
After deletion: [ 1  2 10  4  5]


In [64]:
# 51. Perform element-wise addition between two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(f"{arr1} + {arr2} = {result}")


[1 2 3] + [4 5 6] = [5 7 9]


In [65]:
# 52. Perform element-wise subtraction: subtract arr2 from arr1.
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(f"{arr1} - {arr2} = {result}")

[10 20 30] - [1 2 3] = [ 9 18 27]


In [66]:
# 53. Perform element-wise multiplication.
arr1 = np.array([2, 3, 4])
arr2 = np.array([5, 6, 7])
result = arr1 * arr2
print(f"{arr1} * {arr2} = {result}")

[2 3 4] * [5 6 7] = [10 18 28]


In [67]:
# 54. Divide elements of arr1 by arr2 element-wise.
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 5, 10])
result = arr1 / arr2
print(f"{arr1} / {arr2} = {result}")

[10 20 30] / [ 2  5 10] = [5. 4. 3.]


In [68]:
# 55. Perform element-wise exponentiation: arr1 ** arr2.
arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 2, 1])
result = arr1 ** arr2
print(f"{arr1} ** {arr2} = {result}")


[2 3 4] ** [3 2 1] = [8 9 4]


In [69]:
# 56. Count occurrences of a substring in a string array.
str_arr = np.array(['apple', 'banana', 'application', 'apricot'])
substring = 'app'
counts = np.char.count(str_arr, substring)
print("Array:", str_arr)
print(f"Occurrences of '{substring}':", counts)

Array: ['apple' 'banana' 'application' 'apricot']
Occurrences of 'app': [1 0 1 0]


In [70]:
# 57. Extract uppercase characters from a string array.
str_arr = np.array(['NumPy', 'Pandas', 'SciPy'])
extract_upper = np.vectorize(lambda x: ''.join([char for char in x if char.isupper()]))
uppers = extract_upper(str_arr)
print("Array:", str_arr)
print("Uppercase characters:", uppers)

Array: ['NumPy' 'Pandas' 'SciPy']
Uppercase characters: ['NP' 'P' 'SP']


In [71]:
# 58. Replace substring occurrences with another string in a string array.
str_arr = np.array(['hello world', 'hello numpy'])
replaced_arr = np.char.replace(str_arr, 'hello', 'hi')
print("Original array:", str_arr)
print("Replaced array:", replaced_arr)


Original array: ['hello world' 'hello numpy']
Replaced array: ['hi world' 'hi numpy']


In [72]:
# 60. Find the length of the longest string in a string array.
str_arr = np.array(['short', 'longer string', 'medium'])
lengths = np.vectorize(len)(str_arr)
max_length = lengths.max()
print("Array:", str_arr)
print("Length of the longest string:", max_length)

Array: ['short' 'longer string' 'medium']
Length of the longest string: 13


In [73]:
# 61. Generate 100 random integers (1-1000) and compute stats.
rand_arr = np.random.randint(1, 1001, 100)
mean = np.mean(rand_arr)
median = np.median(rand_arr)
variance = np.var(rand_arr)
std_dev = np.std(rand_arr)
print(f"Mean: {mean:.2f}")
print(f"Median: {median}")
print(f"Variance: {variance:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")



Mean: 494.81
Median: 482.0
Variance: 67572.99
Standard Deviation: 259.95


In [74]:
# 62. Generate 50 random numbers (1-100) and compute percentiles.
rand_arr = np.random.randint(1, 101, 50)
p25 = np.percentile(rand_arr, 25)
p75 = np.percentile(rand_arr, 75)
print(f"25th Percentile (Q1): {p25}")
print(f"75th Percentile (Q3): {p75}")

25th Percentile (Q1): 39.0
75th Percentile (Q3): 82.0


In [75]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10]) 
corr_matrix = np.corrcoef(arr1, arr2)
print("Correlation matrix:\n", corr_matrix)
print(f"Correlation coefficient: {corr_matrix[0, 1]:.2f}")

Correlation matrix:
 [[1. 1.]
 [1. 1.]]
Correlation coefficient: 1.00


In [76]:
# 64. Perform matrix multiplication using np.dot.
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(mat1, mat2)
matmul_product = mat1 @ mat2
print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("Dot Product:\n", dot_product)
print("Matmul (@) Product:\n", matmul_product)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Dot Product:
 [[19 22]
 [43 50]]
Matmul (@) Product:
 [[19 22]
 [43 50]]


In [77]:
# 65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.
rand_arr = np.random.randint(1, 1001, 50)
percentiles = [10, 50, 90]
quartiles = [25, 50, 75] 
p_values = np.percentile(rand_arr, percentiles)
q_values = np.percentile(rand_arr, quartiles)
print(f"10th, 50th, 90th percentiles: {p_values}")
print(f"Quartiles (25th, 50th, 75th): {q_values}")

10th, 50th, 90th percentiles: [ 62.9 519.  908.8]
Quartiles (25th, 50th, 75th): [209.25 519.   755.25]


In [78]:
# 66. Find index of a specific element in an array.
arr = np.array([10, 20, 30, 40, 50, 30])
element_to_find = 30
indices = np.where(arr == element_to_find)
print("Array:", arr)
print(f"Indices of element {element_to_find}:", indices[0])

Array: [10 20 30 40 50 30]
Indices of element 30: [2 5]


In [79]:
# 67. Sort a random array in ascending order.
rand_arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(rand_arr)
print("Original random array:", rand_arr)
print("Sorted array:", sorted_arr)


Original random array: [37 57 17 62 38 12 51 42 62 21]
Sorted array: [12 17 21 37 38 42 51 57 62 62]


In [80]:
# 68. Filter elements greater than 20.
arr = np.array([5, 25, 15, 30, 10])
filtered = arr[arr > 20]
print("Array:", arr)
print("Elements > 20:", filtered)


Array: [ 5 25 15 30 10]
Elements > 20: [25 30]


In [81]:
# 69. Filter elements divisible by 3.
arr = np.arange(1, 11)
filtered = arr[arr % 3 == 0]
print("Array:", arr)
print("Elements divisible by 3:", filtered)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Elements divisible by 3: [3 6 9]


In [82]:
# 70. Filter elements between 20 and 40 (inclusive).
arr = np.arange(10, 51)
filtered = arr[(arr >= 20) & (arr <= 40)]
print("Array Start/End:", arr[0], arr[-1])
print("Elements between 20 and 40:", filtered)

Array Start/End: 10 50
Elements between 20 and 40: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [87]:
# 71. Check byte order of a NumPy array using dtype.byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
order_map = {'=': 'Native', '<': 'Little-Endian', '>': 'Big-Endian'}
print("Byte order symbol:", byte_order)
print("Byte order:", order_map.get(byte_order, "Unknown"))


Byte order symbol: =
Byte order: Native


In [85]:
# 72. Perform in-place byte swapping using byteswap().
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
print("Original array (hex):", [hex(x) for x in arr])
swapped_arr = arr.byteswap(inplace=True)
print("Swapped array:", swapped_arr)
print("Swapped array (hex):", [hex(x) for x in swapped_arr])

Original array: [1 2 3]
Original array (hex): ['0x1', '0x2', '0x3']
Swapped array: [16777216 33554432 50331648]
Swapped array (hex): ['0x1000000', '0x2000000', '0x3000000']
